### ISSUE TITLE
[1.12.2] Biome IDs?

### ISSUE THREAD

**Issue by xJon** [JarHax/Caliper#20]
The biome Registry Analysis, unlike the dimension one, does not contain a list of all taken biome IDs. Is that intentional? Is there any alternative for checking biome ID conflicts?
Thank you!

**Comment by Darkhax** [comment]
Thanks for reaching out. The biome profiler is just a standard Forge registry profiler such as item/block which is why it does not include the numeric ID info. I will mark your issue as a feature enhancement. I think instead of listing IDs I will just document duplicate IDs for potions and biomes in the error file.

**Comment by xJon** [comment]
That does sound good as [Anti Id Conflict](https://www.curseforge.com/minecraft/mc-mods/anti-id-conflict) has not been updated for 1.12.2. I did use [TellMe](https://www.curseforge.com/minecraft/mc-mods/tellme) to find out the IDs.

**Comment by Darkhax** [comment]
I am not planning to do any more feature updates for 1.12, and in newer versions we have unlimited ids and Forge's registry dumper so this feature is no longer needed.
